match/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),

]

match/match/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('team/',include("team.urls", namespace="team")),
]

match/team/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'team'

urlpatterns = [
    path('',views.ListTeam.as_view(),name='all'),
    path('new/',views.CreateTeam.as_view(),name='createteam'),
    path('detail/in/<slug>/',views.SingleTeam.as_view(),name='teamdetail'),
    path('setmatch/',views.CreateMatch.as_view(),name='creatematch'),
    path('matchlist/',views.ListMatch.as_view(),name='matchlist'),

 ]

match/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "{}".format(self.username)

    

match/team/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify
from django.conf import settings

User = get_user_model()

# Create your models here.


class team(models.Model):
    userid = models.OneToOneField('auth.User',on_delete=models.CASCADE)
    slug = models.SlugField(allow_unicode=True, unique=True)
    team_name = models.CharField(max_length=256, unique=True)
    team_motto = models.TextField()
    contact_no = models.CharField(max_length=10)
    location = models.CharField(max_length=256)
    confirm = models.BooleanField(default=False)

    def __str__(self):
        return self.team_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.team_name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("team:teamdetail", kwargs={"slug": self.slug})


class matchset(models.Model):
    match_date = models.DateTimeField()
    team1 = models.ForeignKey(team,related_name='one', blank=True, default='',on_delete=models.CASCADE)
    team2 = models.ForeignKey(team,related_name='two', blank=True, default='', on_delete=models.CASCADE)
    match_location = models.CharField(max_length=200)

    def __str__(self):
        return "{} VS {}".format(self.team1,self.team2)

    def get_absolute_url(self):
        return reverse("team:matchlist")

match/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "User name"
        self.fields["email"].label = "Email address"

match/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
from team.models import team

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

match/match/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'team/test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

match/team/views.py
from django.shortcuts import render
from .models import team, matchset
from django.views.generic import (CreateView, TemplateView,
                                 ListView, DetailView)
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
# Create your views here.
class CreateTeam(LoginRequiredMixin, CreateView):
    fields = ( "userid", "team_name", "team_motto", "contact_no", "location", "confirm")
    model = team

class SingleTeam(LoginRequiredMixin, DetailView):
    model = team

class ListTeam(ListView):
    model = team

class CreateMatch(LoginRequiredMixin, CreateView):
    fields = ("match_date", "team1", "team2", "match_location")
    model = matchset

class ListMatch(ListView):
    model = matchset

match/accounts/templates/accounts/login.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h2>Login</h2>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

match/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h2>Sign Up</h2>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

match/team/templates/team/matchset_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h2>Match Creation</h2>
  <form method="POST" action="{% url 'team:creatematch' %}"class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Done</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

match/team/templates/team/matchset_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h4>Schedule of Upcoming Matches are shown.</h4><br>
    {% for matchset in object_list %}
    <ul>
      <li>{{matchset.team1}} VS {{matchset.team2}}.<br>
      Match Date : {{matchset.match_date}}<br>
      Venue : {{matchset.match_location}}</li>
    </ul>

    {% endfor %}

  </div>
</div>
{% endblock %}

match/team/templates/team/team_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h3>{{team.team_name}}</h3>
    <h4>Created by : {{team.userid}}</h4>
    <ul>
      <li><h5>Team motto : {{team.team_motto}}</h5></li>
      <li><h5>Contact No : {{team.contact_no}}</h5></li>
      <li><h5>Location : {{team.location}}</h5></li>
    </ul>
  </div>
</div>
{% endblock %}

match/team/templates/team/team_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h2>Team Creation</h2>
  <form method="POST" action="{% url 'team:createteam' %}"class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Done</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

match/team/templates/team/team_list.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    
    <h4>The Football Teams that are oficially registered
      on this website are shown below.</h4><br>

    {% for team in object_list %}
    <ul>
      <li><a href="{% url 'team:teamdetail' slug=team.slug %}">
          <h4>{{team.team_name}}</h4>
        </a>
      </li>
    </ul>

    {% endfor %}

  </div>
</div>
{% endblock %}

match/team/templates/team/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h2>{{user.username}} is logged in!</h2><br>

    <h3><a href="{% url 'team:all' %}">Go to Teams ></a></h3><br>
    {% for team in object_list %}
      <h1>team.userid</h1>
      {% endfor %}

        <a href="{% url 'team:createteam' %}" class="btn btn-warning" >+Create Team</a>



  </div>

</div>

{% endblock %}

match/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">THE MATCH</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'team:matchlist' %}" class="btn btn-simple">Upcoming Matches</a>
            <a class="nav-item nav-link" href="{% url 'team:all' %}" class="btn btn-simple">Team List</a>
            <a class="nav-item nav-link" href="{% url 'team:creatematch' %}" class="btn btn-simple">Create Match</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'team:matchlist' %}" class="btn btn-simple">Upcoming Matches</a>
            <a class="nav-item nav-link" href="{% url 'team:all' %}"class="btn btn-simple">Team List</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}
      </div>

  </body>
</html>

match/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container mycontent">
  <div class="jumbotron">

<h1>THE MATCH</h1>
<h5>BUILD | PLAY | UNITE</h5>
<div class="container">
  <img src="{% static "match/images/match2.jpg" %}" alt="">
</div><br>
<p>THE MATCH! This is a official website for Football Players.</p>
<p>The site allows you to create football matches between friends in your
  locality or even in other areas. The team organiser can organize
  the match with other teams by making a schedule. A team can be created by going
  to the SignUp page, Each team will be under unique user name. So
  Build your team, play the match and unite with more people.</p>
  <h6>Let THE MATCH break your boundaries and limits!.</h6>

</div>
</div>

{% endblock %}

match/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
<h1>Thanks for visiting! Come back soon!</h1>
  </div>
</div>

{% endblock %}